src/main/java/ru/kpfu/itis/group11501/vitise/model/User.java
package ru.kpfu.itis.group11501.vitise.model;

import ru.kpfu.itis.group11501.vitise.model.enums.StatusName;

import javax.persistence.*;

@Entity
@Table(name = "users")
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    private String surname;

    @Column(name = "third_name")
    private String thirdName;

    @Column(name = "is_active")
    private Boolean isActive;

    private String email;

    private String password;

    @Column(name = "photo_name")
    private String photoName;

    @Column(name = "telephone_number")
    private String telephoneNumber;

    private String description;

    @Column(name = "pass_must_be_changed")
    private boolean passMustBeChanged;

    @Column
    private boolean confirmed;

    @Column(name = "confirmation_token")
    private String token;

    @Column(name = "new_email")
    private String newEmail;

    @Column(name = "new_password")
    private String newPassword;

    @Transient
    private Group group;

    @Transient
    private StatusName status;

    @Transient
    private String generatingPassword;

    public User() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getThirdName() {
        return thirdName;
    }

    public void setThirdName(String thirdName) {
        this.thirdName = thirdName;
    }

    public Boolean isActive() {
        return isActive;
    }

    public void setActive(Boolean active) {
        isActive = active;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPhotoName() {
        return photoName;
    }

    public void setPhotoName(String photoName) {
        this.photoName = photoName;
    }

    public String getTelephoneNumber() {
        return telephoneNumber;
    }

    public void setTelephoneNumber(String telephoneNumber) {
        this.telephoneNumber = telephoneNumber;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public boolean isPassMustBeChanged() {
        return passMustBeChanged;
    }

    public void setPassMustBeChanged(boolean passMustBeChanged) {
        this.passMustBeChanged = passMustBeChanged;
    }

    public boolean equals(Object obj) {
        return obj instanceof User && this.getId().equals(((User) obj).getId());
    }

    public String getFullName() {
        return this.surname + " " + this.name + " " + this.thirdName;
    }

    public Group getGroup() {
        return group;
    }

    public void setGroup(Group group) {
        this.group = group;
    }

    public StatusName getStatusName() {
        return status;
    }

    public void setStatusName(StatusName status) {
        this.status = status;
    }

    public boolean isConfirmed() {
        return confirmed;
    }

    public void setConfirmed(boolean confirmed) {
        this.confirmed = confirmed;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public StatusName getStatus() {
        return status;
    }

    public void setStatus(StatusName status) {
        this.status = status;
    }

    public String getNewEmail() {
        return newEmail;
    }

    public void setNewEmail(String newEmail) {
        this.newEmail = newEmail;
    }

    public String getGeneratingPassword() {
        return generatingPassword;
    }

    public void setGeneratingPassword(String generatingPassword) {
        this.generatingPassword = generatingPassword;
    }

    public String getNewPassword() {
        return newPassword;
    }

    public void setNewPassword(String newPassword) {
        this.newPassword = newPassword;
    }
}

src/main/java/ru/kpfu/itis/group11501/vitise/pojo/Message.java
package ru.kpfu.itis.group11501.vitise.pojo;

/**
 * Created by Bogdan Popov on 26.04.2017.
 */
public class Message {
    private String content;

    public Message() {
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }
}

src/main/java/ru/kpfu/itis/group11501/vitise/controller/ColleaguesController.java
package ru.kpfu.itis.group11501.vitise.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;
import ru.kpfu.itis.group11501.vitise.model.User;
import ru.kpfu.itis.group11501.vitise.service.ColleaguesService;
import ru.kpfu.itis.group11501.vitise.service.UserService;

import javax.servlet.http.HttpServletRequest;

/**
 * Created by Наталья on 22.03.2017.
 */
@Controller
@RequestMapping("/colleagues")
public class ColleaguesController {
    private final ColleaguesService colleaguesService;
    private final UserService userService;

    @Autowired
    public ColleaguesController(ColleaguesService colleaguesService, UserService userService) {
        this.colleaguesService = colleaguesService;
        this.userService = userService;
    }

    @RequestMapping(value = "/{id}/add", method = RequestMethod.POST)
    public String addColleague(@PathVariable(name = "id") String idUser, HttpServletRequest request) {
        User currentUser = (User) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
        User user = userService.findOne(Long.valueOf(idUser));
        colleaguesService.add(currentUser, user);
        return "redirect:" + request.getHeader("Referer");
    }

    @RequestMapping(value = "/{id}/approve", method = RequestMethod.POST)
    public String approveColleague(@PathVariable(name = "id") String idColleague, HttpServletRequest request) {
        colleaguesService.approve(Long.valueOf(idColleague));
        return "redirect:" + request.getHeader("Referer");
    }

    @RequestMapping(value = "/{id}/delete", method = RequestMethod.POST)
    public String deleteColleague(@PathVariable(name = "id") String idColleague, HttpServletRequest request) {
        colleaguesService.delete(Long.valueOf(idColleague));
        return "redirect:" + request.getHeader("Referer");
    }

    @RequestMapping("")
    public String pageColleagues(Model model) {
        User currentUser = (User) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
        model.addAttribute("myrequests", colleaguesService.getRequestSender(currentUser));
        model.addAttribute("requests", colleaguesService.getRequestReceiver(currentUser));
        model.addAttribute("colleagues", colleaguesService.getAllColleagues(currentUser));
        model.addAttribute("currentUser", currentUser);
        return "colleagues";
    }

    @RequestMapping(value = "/get_number")
    @ResponseBody
    public Integer getRequestsNumber(@RequestParam(name = "requests", required = false) int requests) {
        User currentUser = (User) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
        return new Integer(colleaguesService.getRequestsCount(currentUser));
    }

}

src/main/java/ru/kpfu/itis/group11501/vitise/controller/ConversationController.java
package ru.kpfu.itis.group11501.vitise.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.messaging.handler.annotation.DestinationVariable;
import org.springframework.messaging.handler.annotation.MessageMapping;
import org.springframework.messaging.simp.SimpMessagingTemplate;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;
import ru.kpfu.itis.group11501.vitise.model.User;
import ru.kpfu.itis.group11501.vitise.model.conversation.Conversation;
import ru.kpfu.itis.group11501.vitise.model.conversation.ConversationMember;
import ru.kpfu.itis.group11501.vitise.model.conversation.ConversationMessage;
import ru.kpfu.itis.group11501.vitise.model.conversation.ConversationMessageFile;
import ru.kpfu.itis.group11501.vitise.model.conversation.enums.ActiveStatusName;
import ru.kpfu.itis.group11501.vitise.pojo.Message;
import ru.kpfu.itis.group11501.vitise.pojo.ResponseMessage;
import ru.kpfu.itis.group11501.vitise.pojo.enums.MessagingType;
import ru.kpfu.itis.group11501.vitise.service.ConversationMessageFileService;
import ru.kpfu.itis.group11501.vitise.service.ConversationService;
import ru.kpfu.itis.group11501.vitise.service.StompSessionService;
import ru.kpfu.itis.group11501.vitise.service.UserService;
import ru.kpfu.itis.group11501.vitise.util.FileUploader;

import javax.servlet.http.HttpServletRequest;
import java.security.Principal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;

/**
 * Author: Svintenok Kate
 * Date: 29.03.2017
 * Group: 11-501
 * Project: vITISe
 */
@Controller
public class ConversationController {
    private final UserService userService;
    private final ConversationService conversationService;
    private final ConversationMessageFileService conversationMessageFileService;
    private final SimpMessagingTemplate messagingTemplate;
    private final StompSessionService stompSessionService;

    @Autowired
    public ConversationController(UserService userService,
                                  ConversationService conversationService, ConversationMessageFileService conversationMessageFileService, SimpMessagingTemplate messagingTemplate, StompSessionService stompSessionService) {
        this.userService = userService;
        this.conversationService = conversationService;
        this.conversationMessageFileService = conversationMessageFileService;
        this.messagingTemplate = messagingTemplate;
        this.stompSessionService = stompSessionService;
    }

    @RequestMapping(value = "/messages/conversation/create", method = RequestMethod.POST)
    public String createConversation(@RequestParam(name = "conversation_name") String name,
                                     @RequestParam(name = "members", required = false) Long[] membersId) {
        User currentUser = (User) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
        List<User> members = new ArrayList<>();
        System.out.println("----------------------------------------------" + name);
        if (membersId != null) {
            for (Long id : membersId)
                members.add(userService.getUser(id));
            Conversation conversation = conversationService.createConversation(name, currentUser, members);
            return "redirect:/messages/conversation/" + conversation.getId();
        }
        return "redirect:/messages/all";
    }

    @RequestMapping(value = "/messages/conversation/{id}")
    public String conversationPage(@PathVariable("id") Long id, Model model) {
        User currentUser = (User) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
        if (conversationService.getMember(currentUser, conversationService.getConversation(id)) == null)
            return "handle404";
        Conversation conversation = conversationService.getConversationWithInfo(id, currentUser);
        ConversationMember member = conversationService.getMember(currentUser, conversation);
        model.addAttribute("currentUser", currentUser);
        model.addAttribute("conversation", conversation);
        model.addAttribute("message_form", new ConversationMessage());
        model.addAttribute("available_users", conversationService.getAvailableUsers(conversation));

        conversationService.updateReadingLog(member);
        return "conversation";
    }

    @MessageMapping("/conversation/send/{id}")
    public void conversationSendMessage(@DestinationVariable Long id,
                                        Message message, Principal principal) {

        Conversation conversation = conversationService.getConversation(id);
        User currentUser = (User) ((UsernamePasswordAuthenticationToken) principal).getPrincipal();
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss", Locale.getDefault());
        ConversationMessage conversationMessage = new ConversationMessage();
        conversationMessage.setText(message.getContent());
        conversationMessage.setUser(currentUser);
        conversationMessage.setConversation(conversation);
        conversationService.addMessage(conversationMessage);
        ResponseMessage responseMessage = new ResponseMessage();
        responseMessage.setNameMessaging(conversation.getName());
        responseMessage.setType(MessagingType.CONVERSATION);
        responseMessage.setDate(dateFormat.format(date));
        responseMessage.setSender(userService.convertToPOJO(currentUser));
        responseMessage.setContent(message.getContent());
        responseMessage.setIdMessaging(String.valueOf(conversation.getId()));
        String destination = "/topic/conversation/" + id;
        messagingTemplate.convertAndSend(destination, responseMessage);
        List<User> conversationMembers = conversationService.getMembers(conversation);
        List<User> users = stompSessionService.getAllUser(destination);
        for (User user : users) {
            conversationService.updateReadingLog(conversationService.getMember(user, conversation));
        }
        conversationMembers.removeAll(users);
        for (User conversationMember : conversationMembers) {
            messagingTemplate.convertAndSend("/topic/messages/" + conversationMember.getId(), responseMessage);
        }
    }

    @RequestMapping(value = "/messages/conversation/{id}/upload")
    public String uploadFile(@PathVariable(name = "id") Long id,
                             @RequestParam(value = "file", required = false) MultipartFile file,
                             HttpServletRequest request) {
        User user = (User) ((UsernamePasswordAuthenticationToken) request.getUserPrincipal()).getPrincipal();
        Conversation conversation = conversationService.getConversation(id);
        ConversationMessage message = conversationService.getLastMessageByUserInConversation(user, conversation);
        ConversationMessageFile conversationMessageFile = new ConversationMessageFile();
        conversationMessageFile.setConversationMessage(message);
        String name = FileUploader.uploadFile(file);
        conversationMessageFile.setFilename(name);
        conversationMessageFileService.add(conversationMessageFile);
        return "redirect:" + request.getHeader("Referer");
    }

    @RequestMapping(value = "/messages/conversation/{id}/change", method = RequestMethod.POST)
    public String conversationChange(@PathVariable("id") Long id,
                                     @RequestParam(name = "name") String name,
                                     @RequestParam(name = "users_id") Long[] usersId) {
        User currentUser = (User) SecurityContextHolder.getContext().getAuthentication().getPrincipal();

        Conversation conversation = conversationService.getConversationWithInfo(id, currentUser);
        conversation.setName(name);
        conversationService.saveConversation(conversation);

        for (User user : this.needToDelete(conversation.getMembers(), usersId)) {
            ConversationMember member = conversationService.getMember(user, conversation);
            conversationService.memberChangeStatus(member, ActiveStatusName.DELETED);
        }
        return "redirect:/messages/conversation/" + id;
    }

    @RequestMapping(value = "/messages/conversation/{id}/add", method = RequestMethod.POST)
    public String conversationAddMember(@PathVariable("id") Long id,
                                        @RequestParam(name = "users_id") Long[] usersId) {
        if (usersId != null) {
            for (Long userId : usersId)
                conversationService.addMember(conversationService.getConversation(id), userService.getUser(userId));
        }
        return "redirect:/messages/conversation/" + id;
    }

    @RequestMapping(value = "/messages/conversation/{id}/change_status", method = RequestMethod.POST)
    public String conversationChangeStatus(@PathVariable("id") Long id,
                                           @RequestParam(name = "user_id") Long userId) {
        ConversationMember member =
                conversationService.getMember(userService.getUser(userId), conversationService.getConversation(id));
        if (member.getActiveStatusName() == ActiveStatusName.ACTIVE)
            conversationService.memberChangeStatus(member, ActiveStatusName.LEFT_OUT);
        else
            conversationService.memberChangeStatus(member, ActiveStatusName.ACTIVE);

src/main/webapp/WEB-INF/templates/courses_requests.ftl
<#include "base2.ftl">
<#macro title>Заявки на курсы</#macro>
<#macro name>${currentUser.name}</#macro>
<#macro link>
<link rel="stylesheet" href="/css/dialogs.css">
<link rel="stylesheet" href="/css/requests.css">
</#macro>
<#macro content>
<div class="main-block">
    <div class="line2" style="padding-top: 30px">
        <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
            <div class="col-xs-12">
                <div class="col-xs-12 input-wrapper">
                    <a href="#"><i class="fa fa-lg fa-chevron-left" aria-hidden="true"></i> &nbsp; &nbsp;</a>
                    <h4 id="title"
                        style="color:rgba(7, 84, 133, 0.8); overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">
                        Заявки на курсы</h4>
                    <input type="text" placeholder="Начните вводить имя или фамилию" class="search-input1"
                           id="message-search-field">
                    <a href="#" id="search-message-btn"><i class="fa fa-lg fa-search" aria-hidden="true"></i></a>
                    <a href="#" id="cancel-search-btn" hidden><i class="fa fa-lg fa-times" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>
    </div>

    <div class="line2">
        <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2" id="messages-block">
            <div class="col-xs-12">
                <div class="col-xs-12 messages-items-block1">
                    <#list requests as req>
                        <div class="message-item">
                            <div class="round-photo">
                                <img src="/img/mal.png" alt="">
                            </div>
                            <div class="message-text">
                                <h4><a href="/user/${req.user.id}">${req.user.fullName}</a></h4>
                                <form method="post" action="/deanery/courses/${req.id}/delete">
                                    <input type="submit" value="Отклонить"
                                           class="news-submit-btn">
                                </form>
                                <form method="post" action="/deanery/courses/${req.id}/approve">
                                    <input type="submit" value="Одобрить"
                                           class="news-submit-btn">
                                </form>
                                <h5>${req.user.group.name}</h5>
                                <h5>Заявка на прохождение курса <a href="/courses/${req.course.id}">${req.course.subject.name}</a></h5>
                            </div>
                        </div>
                    </#list>
                </div>
            </div>
        </div>

    </div>

</div>
<script>
    $('.friend').click(function () {
        $(this).find('input[type=checkbox]').prop("checked", !$(this).find('input[type=checkbox]').prop("checked"));
    });

    function auto_grow(element) {
        element.style.height = "auto";
        element.style.height = (element.scrollHeight) + "px";
    }

    $('.post-input').keypress(function () {
        $('#buttons').show();
    });

    $('#submit-btn').click(function () {
        $('#buttons').hide();
        $('.post-input').val('');
    });


    $(function () {
        $('.messages-items-block').scrollTop(1E10);
    });

    $('#search-message-btn').click(function () {
        $(this).hide();
        $('#title').hide();
        $('#message-search-field').show('fast');
        $('#cancel-search-btn').show();
    });

    $('#cancel-search-btn').click(function () {
        $(this).hide();
        $('#title').show('fast');
        $('#message-search-field').hide();
        $('#search-message-btn').show();
    });


</script>

</#macro>

src/main/webapp/WEB-INF/templates/create_course.ftl
<#include "base2.ftl">
<#macro title>Создание курса</#macro>
<#macro name>${currentUser.name}</#macro>
<#macro link>
<link rel="stylesheet" href="/css/login.css">
<link rel="stylesheet" href="/css/labs.css">
</#macro>
<#macro content>
<div class="main-block">

    <div class="col-lg-6 col-md-8 col-lg-offset-3 col-md-offset-2 col-sm-8 col-sm-offset-2 login-block">

        <h2 class="title">Создание Курса</h2>
        <form action="/deanery/courses/create" method="post">
            <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                <p class="input-label">Название</p>
                <div class="input-wrapper2" style="margin-top: 30px">
                    <input type="text" class="login-input" name="name" placeholder="Введите название">
                </div>
                <p>&nbsp; </p>
                <div class="selects">
                    <p class="input-label">Преподаватель курса</p>
                    <div class="input-wrapper">
                        <select class="login-input" name="teacher">
                            <#list teachers as t>
                                <option value="${t.id}">${t.fullName}</option>
                            </#list>
                        </select>
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                <p class="input-label">Описание курса</p>
                <textarea name="description" placeholder="Напишите о курсе дополнительную информацию"
                          class="input-wrapper1"></textarea>
            </div>

            <div class="row">
                <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                    <div class="col-md-8 col-lg-7 col-xs-12 col-sm-12 col-md-offset-4 col-lg-offset-5">
                        <input type="submit" value="Создать" class="login-btn">
                    </div>
                </div>

                <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                    <div class="col-md-7 col-lg-6 col-xs-12 col-sm-12">
                        <h3 class="links"><a href="/courses">Отмена</a></h3>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    $("#signup-btn").click(function () {
        $("#modal-form").show();
    })

    var mouse_is_inside = false;
    $(document).ready(function () {
        $('#modal-form').hover(function () {
            mouse_is_inside = true;
        }, function () {
            mouse_is_inside = false;
        });

        $("body").mouseup(function () {
            if (!mouse_is_inside) $('#modal-form').hide();
        });
    });
</script>
</#macro>

src/main/webapp/WEB-INF/templates/create_laboratory.ftl
<#include "base2.ftl">
<#macro title>Создание лаборатории</#macro>
<#macro name>${currentUser.name}</#macro>
<#macro link>
<link rel="stylesheet" href="/css/login.css">
<link rel="stylesheet" href="/css/labs.css">
</#macro>
<#macro content>
<div class="main-block">

    <div class="col-lg-6 col-md-8 col-lg-offset-3 col-md-offset-2 col-sm-8 col-sm-offset-2 login-block no-mh">

        <h3 class="title">Создание лаборатории</h3>
        <form action="/deanery/laboratories/create" method="post">
            <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                <p class="input-label">Название</p>
                <div class="input-wrapper2" style="margin-top: 30px">
                    <input type="text" class="login-input" name="name" placeholder="Введите название">
                </div>
                <p>&nbsp; </p>
                <div class="selects">
                    <p class="input-label">Научное направление</p>
                    <div class="input-wrapper">
                        <select class="login-input" name="direction">
                            <#list directions as d>
                                <option value="${d.id}">${d.name}</option>
                            </#list>
                        </select>
                    </div>
                </div>
                <p>&nbsp; </p>
                <div class="selects">
                    <p class="input-label">Научный руководитель</p>
                    <div class="input-wrapper">
                        <select class="login-input" name="teacher">
                            <#list teachers as t>
                                <option value="${t.id}">${t.fullName}</option>
                            </#list>
                        </select>
                    </div>
                </div>

            </div>

            <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                <p class="input-label">Описание</p>
                <textarea name="description" placeholder="Напишите о лаборатории дополнительную информацию"
                          class="input-wrapper1"></textarea>
            </div>

            <div class="row">
                <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                    <div class="col-xs-12">
                    <#--<div class="col-md-8 col-lg-7 col-xs-12 col-sm-12 col-md-offset-4 col-lg-offset-5">-->
                        <h3 class="links cancel"><a href="/laboratories">Отмена</a></h3>
                        <input type="submit" value="Создать" class="login-btn">
                    </div>
                <#--</div>-->
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    $("#signup-btn").click(function () {
        $("#modal-form").show();
    })

    var mouse_is_inside = false;
    $(document).ready(function () {
        $('#modal-form').hover(function () {
            mouse_is_inside = true;
        }, function () {
            mouse_is_inside = false;
        });

        $("body").mouseup(function () {
            if (!mouse_is_inside) $('#modal-form').hide();
        });
    });
</script>
</#macro>

src/main/webapp/WEB-INF/templates/handle404.ftl
<h1>404 Not Found</h1>

src/main/webapp/WEB-INF/templates/laboratory.ftl
<#include "base2.ftl">
<#macro title>Лаборатория ${laboratory.name}</#macro>
<#macro name>${currentUser.name}</#macro>
<#macro link>
<link rel="stylesheet" href="/css/news-profile.css"></#macro>
<#macro content>
    <#assign sf=JspTaglibs["http://www.springframework.org/tags/form"]>
<div class="main-block">
    <div class="line1">
        <div class="col-md-10 col-md-offset-1 col-sm-12 col-xs-12">

            <div class="col-md-3 col-sm-4">
                <div class="col-md-12 photo-block">
                    <div class="photo-border">
                        <img class="profile-photo" src="/img/bg3.png" alt="">
                    </div>
                </div>
            </div>

            <div class="col-md-9 col-sm-8">
                <div class="col-md-12 info-block">
                    <h2 style="color: #1b6d85;">${laboratory.name}</h2>
                    <p>Информация о лаборатории: &nbsp; &nbsp;&nbsp;<span
                            class="about-text">${laboratory.description}</span></p>
                    <p>Научный руководитель: &nbsp; &nbsp;&nbsp;<a href="/user/${laboratory.head.id}">${laboratory.head.fullName}</a></p>
                    <p>Направление: &nbsp; &nbsp;&nbsp;<a href="#">${laboratory.direction.name}</a></p>
                    <#if is_student>
                        <#if state == 0>
                            <form method="post" action="/laboratories/enroll">
                                <input value="${laboratory.id}" name="id" hidden>
                                <button type="submit" class="modify-btn">Записаться в лабораторию</button>
                            </form>
                        <#elseif state == 1>
                            <form method="post" action="/laboratories/${laboratory.id}/decline">
                                <input hidden name="id" value="${request_id}">
                                <button type="submit" class="modify-btn">Отменить заявку</button>
                            </form>
                        <#elseif state == 2>
                            <p>Вы уже состоите в этой лаборатории</p>
                        <#else>
                            <p>Вы не можете подать заявку</p>
                        </#if>
                    </#if>
                </div>
            </div>

        </div>
    </div> <!-- line1 -->

    <div class="line1">
        <div class="col-md-10 col-md-offset-1 col-sm-12 col-xs-12 post">
            <div class="col-md-12">
                <div class="col-md-12 post-block">
                    <#if students?has_content>
                        <h3>Студенты в лаборатории (${students_amount})</h3>
                        <#list students as s>
                            <h4><a href="/user/${s.id}">${s.fullName}</a></h4>
                        </#list>
                    <#else>
                        <h3>Нет студентов в лабораотрии. Запишись, будь первым!</h3>
                    </#if>
                </div>
            </div>
        </div>
    </div>
</div>
</#macro>

src/main/webapp/WEB-INF/templates/support.ftl
<#include "base1.ftl">
<#macro title>Поддержка</#macro>
<#macro content>
    <#assign sf=JspTaglibs["http://www.springframework.org/tags/form"]>

<div class="main-block">
    <form method="post" action="/support">
        <input name="message" type="text">
        <input type="submit" value="Отправить">
    </form>

</div>

</#macro>